run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - gosec
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - unconvert

linters-settings:
  revive:
    rules:
      - name: exported
        arguments: [false]
  gosec:
    excludes:
      - G204 # Subprocess launched with variable
  errcheck:
    check-type-assertions: true
    check-blank: true

issues:
  exclude-rules:
    - path: "_test\\.go"
      linters:
        - gosec
        - revive
  max-issues-per-linter: 0
  max-same-issues: 0 