name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_on_macos:

    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Install dependencies
      run: |
        go get golang.org/x/tools/cmd/goimports@latest
        go get github.com/golangci/golangci-lint/cmd/golangci-lint@latest

    - name: Lint
      run: |
        make lint || true

    - name: Build
      run: |
        mkdir bin
        GOARCH=arm64 go build -ldflags="-s -w" -o mobilectl-arm64
        GOARCH=amd64 go build -ldflags="-s -w" -o mobilectl-amd64
        lipo mobilectl-arm64 mobilectl-amd64 -create -output mobilectl
        rm mobilectl-arm64 mobilectl-amd64

    - name: Upload macos build artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-build
        path: |
          mobilectl
        retention-days: 1
        overwrite: true

  publish:

    runs-on: ubuntu-latest
    needs: build_on_macos
    steps:
    - uses: actions/checkout@v4

    - name: Download macos build
      uses: actions/download-artifact@v4
      with:
        name: macos-build
        path: mobilectl-macos

    - uses: AButler/upload-release-assets@v2.0
      with:
        files: "*.zip"
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        release-tag: ${{ env.release_tag }}

    - name: Publish NPM
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      run: |
        # prepare binaries for distribution
        mv ./mobilectl-macos/mobilectl publish/npm/bin/mobilectl
        chmod +x publish/npm/bin/mobilectl
        # setup npmrc
        echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" >> ~/.npmrc
        # sed -i 's/\"local-build\"/\"${{ env.release_tag }}\"/' package.json
        # publish to npm
        cd publish/npm
        npm install
        npm publish
